### ISSUE TITLE
vtex watch -s doesn't work on this repo

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/search-bar#4]

**Comment by tamorim** [comment]
@dfosco Still doesnt work?

**Comment by brenoc** [comment]
@tamorim I think it might not work because of how we are rendering the component in the theme. The component is not registered in the ComponentStore again when is hot loaded, thus it doesn't re-render.

I have to get a way of working this out. Maybe hacking react-transform-hmr or developing a plugin of babel on that matter.

**Comment by brenoc** [comment]
Areas made it work again! :smile:
